version: "3.7"

services:
  web:
    image: cynax/php:7.4-fpm
    volumes:
      - .:/var/www/html
    ports:
      - 3000:8000
    command: bash -c 'php artisan serve --host=0.0.0.0'
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USERNAME: cynax
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: nta

    ports:
      - 3306:3306
